In [ ]:
import pandas as pd
import numpy as np
import random


# из sklearn мы импортируем алгоритм k-ближайших соседей
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [ ]:
df = pd.read_csv('/content/used_cars.csv')
df

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,Ford,Utility Police Interceptor Base,2013,"51,000 mi.",E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,"$10,300"
1,Hyundai,Palisade SEL,2021,"34,742 mi.",Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,Yes,"$38,005"
2,Lexus,RX 350 RX 350,2022,"22,372 mi.",Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,NaN,"$54,598"
3,INFINITI,Q50 Hybrid Sport,2015,"88,900 mi.",Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...,7-Speed A/T,Black,Black,None reported,Yes,"$15,500"
4,Audi,Q3 45 S line Premium Plus,2021,"9,835 mi.",Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,NaN,"$34,999"
...,...,...,...,...,...,...,...,...,...,...,...,...
4004,Bentley,Continental GT Speed,2023,714 mi.,Gasoline,6.0L W12 48V PDI DOHC Twin Turbo,8-Speed Automatic with Auto-Shift,C / C,Hotspur,None reported,Yes,"$349,950"
4005,Audi,S4 3.0T Premium Plus,2022,"10,900 mi.",Gasoline,349.0HP 3.0L V6 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Black,Black,None reported,Yes,"$53,900"
4006,Porsche,Taycan,2022,"2,116 mi.",NaN,Electric,Automatic,Black,Black,None reported,NaN,"$90,998"
4007,Ford,F-150 Raptor,2020,"33,000 mi.",Gasoline,450.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,A/T,Blue,Black,None reported,Yes,"$62,999"
4008,BMW,X3 xDrive30i,2020,"43,000 mi.",Gasoline,248.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,A/T,Gray,Brown,At least 1 accident or damage reported,Yes,"$40,000"

In [ ]:
df = df.drop(columns=['engine', 'int_col', 'fuel_type', 'model', 'ext_col', 'clean_title'], axis=1)

In [ ]:
df

,brand,model_year,milage,transmission,accident,price
0,Ford,2013,"51,000 mi.",6-Speed A/T,At least 1 accident or damage reported,"$10,300"
1,Hyundai,2021,"34,742 mi.",8-Speed Automatic,At least 1 accident or damage reported,"$38,005"
2,Lexus,2022,"22,372 mi.",Automatic,None reported,"$54,598"
3,INFINITI,2015,"88,900 mi.",7-Speed A/T,None reported,"$15,500"
4,Audi,2021,"9,835 mi.",8-Speed Automatic,None reported,"$34,999"
...,...,...,...,...,...,...
4004,Bentley,2023,714 mi.,8-Speed Automatic with Auto-Shift,None reported,"$349,950"
4005,Audi,2022,"10,900 mi.",Transmission w/Dual Shift Mode,None reported,"$53,900"
4006,Porsche,2022,"2,116 mi.",Automatic,None reported,"$90,998"
4007,Ford,2020,"33,000 mi.",A/T,None reported,"$62,999"
4008,BMW,2020,"43,000 mi.",A/T,At least 1 accident or damage reported,"$40,000"

In [ ]:
x = df.drop('price', axis=1)
y = df['price']

In [ ]:
y = y.apply(lambda x: int(x.replace('$', '').replace(',','')))

In [ ]:
! pip install category_encoders

Requirement already satisfied: category_encoders in /usr/local/lib/python3.10/dist-packages (2.6.3)
Requirement already satisfied: numpy>=1.14.0 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (1.26.4)
Requirement already satisfied: scikit-learn>=0.20.0 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (1.3.2)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (1.13.1)
Requirement already satisfied: statsmodels>=0.9.0 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (0.14.2)
Requirement already satisfied: pandas>=1.0.5 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (2.1.4)
Requirement already satisfied: patsy>=0.5.1 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (0.5.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0.5->category_encoders) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0.5->category_encoders) (2024.1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0.5->category_encoders) (2024.1)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from patsy>=0.5.1->category_encoders) (1.16.0)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.20.0->category_encoders) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.20.0->category_encoders) (3.5.0)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.10/dist-packages (from statsmodels>=0.9.0->category_encoders) (24.1)

In [ ]:
from category_encoders.target_encoder import TargetEncoder
from category_encoders.one_hot import OneHotEncoder
from category_encoders.ordinal import OrdinalEncoder

encoder = TargetEncoder(cols=['brand', 'transmission'], smoothing=1)
encoder1 = OneHotEncoder()
encoder2 = OrdinalEncoder()

In [ ]:
x['milage'] = x['milage'].apply(lambda x: int(x.replace(' mi.', '').replace(',','')))

In [ ]:
x

,brand,model_year,milage,transmission,accident
0,Ford,2013,51000,6-Speed A/T,At least 1 accident or damage reported
1,Hyundai,2021,34742,8-Speed Automatic,At least 1 accident or damage reported
2,Lexus,2022,22372,Automatic,None reported
3,INFINITI,2015,88900,7-Speed A/T,None reported
4,Audi,2021,9835,8-Speed Automatic,None reported
...,...,...,...,...,...
4004,Bentley,2023,714,8-Speed Automatic with Auto-Shift,None reported
4005,Audi,2022,10900,Transmission w/Dual Shift Mode,None reported
4006,Porsche,2022,2116,Automatic,None reported
4007,Ford,2020,33000,A/T,None reported
4008,BMW,2020,43000,A/T,At least 1 accident or damage reported

In [ ]:
accident = encoder1.fit_transform(x['accident'])

In [ ]:
#milage = encoder2.fit_transform(x['milage'])

Warning: No categorical columns found. Calling 'transform' will only return input data.

In [ ]:
x['model_year'] = x['model_year'].astype(str)
year = encoder2.fit_transform(x['model_year'])

In [ ]:
x = x.drop('milage', axis=1)
x.insert(loc=2,column='milage', value=milage)

In [ ]:
x = x.drop('model_year', axis=1)
x.insert(loc=1,column='model_year', value=year)

In [ ]:
x1 = x.drop('accident', axis=1)
x = pd.concat([x1, accident], axis='columns', join='outer')
x

,brand,model_year,milage,transmission,accident_1,accident_2,accident_3
0,Ford,1,51000,6-Speed A/T,1,0,0
1,Hyundai,2,34742,8-Speed Automatic,1,0,0
2,Lexus,3,22372,Automatic,0,1,0
3,INFINITI,4,88900,7-Speed A/T,0,1,0
4,Audi,2,9835,8-Speed Automatic,0,1,0
...,...,...,...,...,...,...,...
4004,Bentley,12,714,8-Speed Automatic with Auto-Shift,0,1,0
4005,Audi,3,10900,Transmission w/Dual Shift Mode,0,1,0
4006,Porsche,3,2116,Automatic,0,1,0
4007,Ford,8,33000,A/T,0,1,0
4008,BMW,8,43000,A/T,1,0,0

In [ ]:
x = x.drop(['accident_2', 'accident_3'], axis=1)
x

,brand,model_year,milage,transmission,accident_1
0,Ford,1,51000,6-Speed A/T,1
1,Hyundai,2,34742,8-Speed Automatic,1
2,Lexus,3,22372,Automatic,0
3,INFINITI,4,88900,7-Speed A/T,0
4,Audi,2,9835,8-Speed Automatic,0
...,...,...,...,...,...
4004,Bentley,12,714,8-Speed Automatic with Auto-Shift,0
4005,Audi,3,10900,Transmission w/Dual Shift Mode,0
4006,Porsche,3,2116,Automatic,0
4007,Ford,8,33000,A/T,0
4008,BMW,8,43000,A/T,1

In [ ]:
x = encoder.fit_transform(x,y)
x

              brand  model_year  milage  transmission  accident_1
0      36240.880829           1   51000  25450.044199           1
1      18946.875000           2   34742  66071.812500           1
2      35668.521472           3   22372  63105.021097           0
3      22927.644068           4   88900  47249.669856           0
4      39907.430000           2    9835  66071.812500           0
...             ...         ...     ...           ...         ...
4004  137553.335244          12     714  44555.504711           0
4005   39907.430000           3   10900  54710.615578           0
4006   88751.298507           3    2116  63105.021097           0
4007   36240.880829           8   33000  31507.603664           0
4008   41072.309333           8   43000  31507.603664           1

[4009 rows x 5 columns]

In [ ]:
df = pd.concat([x,y],axis='columns', join='outer')
df

              brand  model_year  milage  transmission  accident_1   price
0      36240.880829           1   51000  25450.044199           1   10300
1      18946.875000           2   34742  66071.812500           1   38005
2      35668.521472           3   22372  63105.021097           0   54598
3      22927.644068           4   88900  47249.669856           0   15500
4      39907.430000           2    9835  66071.812500           0   34999
...             ...         ...     ...           ...         ...     ...
4004  137553.335244          12     714  44555.504711           0  349950
4005   39907.430000           3   10900  54710.615578           0   53900
4006   88751.298507           3    2116  63105.021097           0   90998
4007   36240.880829           8   33000  31507.603664           0   62999
4008   41072.309333           8   43000  31507.603664           1   40000

[4009 rows x 6 columns]

In [ ]:
scaler = StandardScaler()
df_new = pd.DataFrame(scaler.fit_transform(df), columns=df.columns)

In [ ]:
df2 = df.join(df_new, rsuffix='_right', how='outer').reset_index(drop=True)
df2

,brand,model_year,milage,transmission,accident_1,price,brand_right,model_year_right,milage_right,transmission_right,accident_1_right,price_right
0,36240.880829,1,51000,25450.044199,1,10300,-0.220925,-1.306982,-0.262336,-0.803890,1.750978,-0.435233
1,18946.875000,2,34742,66071.812500,1,38005,-0.839743,-1.160593,-0.573255,1.054662,1.750978,-0.083204
2,35668.521472,3,22372,63105.021097,0,54598,-0.241405,-1.014204,-0.809820,0.918923,-0.571109,0.127633
3,22927.644068,4,88900,47249.669856,0,15500,-0.697302,-0.867816,0.462467,0.193500,-0.571109,-0.369160
4,39907.430000,2,9835,66071.812500,0,34999,-0.089728,-1.160593,-1.049579,1.054662,-0.571109,-0.121399
...,...,...,...,...,...,...,...,...,...,...,...,...
4004,137553.335244,12,714,44555.504711,0,349950,3.404261,0.303294,-1.224010,0.070234,-0.571109,3.880478
4005,39907.430000,3,10900,54710.615578,0,53900,-0.089728,-1.014204,-1.029212,0.534857,-0.571109,0.118764
4006,88751.298507,3,2116,63105.021097,0,90998,1.658015,-1.014204,-1.197198,0.918923,-0.571109,0.590144
4007,36240.880829,8,33000,31507.603664,0,62999,-0.220925,-0.282261,-0.606569,-0.526741,-0.571109,0.234379
4008,41072.309333,8,43000,31507.603664,1,40000,-0.048046,-0.282261,-0.415328,-0.526741,1.750978,-0.057854

In [ ]:
year_new = df2.loc[df2['model_year'] == 2021, 'model_year_right']
year_new

1      -1.160593
4      -1.160593
8      -1.160593
10     -1.160593
12     -1.160593
          ...
3961   -1.160593
3962   -1.160593
3971   -1.160593
3993   -1.160593
4000   -1.160593
Name: model_year_right, Length: 350, dtype: float64

In [ ]:
x = df_new.drop('price', axis=1)
y = df_new['price']

In [ ]:
x_train, x_test, y_train, y_test =  train_test_split(x, y, test_size=0.25, random_state=125)

In [ ]:
model = LinearRegression()
model.fit(x_train, y_train)
pred = model.predict(x_test)

In [ ]:
MSE = mean_squared_error(pred, y_test)
MSE

0.17484910673472848

In [ ]:
x_train

         brand  model_year    milage  transmission  accident_1
896  -0.503962   -1.160593 -0.478256      1.054662   -0.571109
1580 -0.443307    1.474403  0.119659     -0.526741   -0.571109
1881 -0.443307    0.156905 -1.386650      0.070129   -0.571109
3910 -0.443307   -1.160593  0.079637     -0.526741   -0.571109
3246  0.477658   -1.306982 -0.183543     -0.803890    1.750978
...        ...         ...       ...           ...         ...
1122  0.345683    1.767180 -0.264801      0.193500   -0.571109
1346 -0.571482   -1.014204 -0.068326      0.370842   -0.571109
3454 -0.089728   -1.160593  1.585946     -0.526741   -0.571109
3437  1.658015    1.767180  1.567754      0.534857   -0.571109
3582  0.477658   -0.282261 -0.907590     -0.526741   -0.571109

[3006 rows x 5 columns]

In [ ]:
df_new2 = df_new.sample(40)
x_new = df_new2.drop('price', axis=1)
y_new = df_new2['price']

In [ ]:
x_train, x_test, y_train, y_test =  train_test_split(x_new, y_new, test_size=0.25, random_state=125)

In [ ]:
model.fit(x_train, y_train)
pred = model.predict(x_test)

In [ ]:
MSE = mean_squared_error(pred, y_test)
MSE

0.10198221273335799